### ISSUE TITLE
Minor: Doesn't work on WP 3.5 and 3.6

### ISSUE THREAD

**Issue by roytanck** [pierre-dargham/multisite-clone-duplicator#10]
I'm forced to use a very old version of WordPress at one of my clients, and I noticed that the Clone Duplicator does not work on 3.6 because it uses wp_get_sites (introduced in 3.7).

Personally, I'd probably fix this by updating the wp.org "requires" tag to 3.7 :).

**Comment by adampatterson** [comment]
4.6 and 4.7, hopefully the PR can be merged in.

**Comment by pierre-dargham** [comment]
Hi,

We just published a new release (1.3.3) :

- We updated the minimum WP required version to 4.0.0

- We fixed the deprecated issue with WP 4.6/4.7 (thank you @adampatterson for reporting it)

https://github.com/pierre-dargham/multisite-clone-duplicator/commit/42b64f7beea91f16dedf7f981490d73e803678db
