### ISSUE TITLE
wp_get_sites is deprecated and throws a Notice

### ISSUE THREAD

**Issue by apermo** [pierre-dargham/multisite-clone-duplicator#15]
https://developer.wordpress.org/reference/functions/wp_get_sites/

wp_get_sites() is used in:

/include/options.php 3x
/lib/functions.php 1x
/template/network_admin_network_settings.php 1x

**Comment by pierre-dargham** [comment]
Hi,

We just published a new release (1.3.3) :

- We updated the minimum WP required version to 4.0.0

- We fixed the deprecated issue with WP 4.6/4.7

https://github.com/pierre-dargham/multisite-clone-duplicator/commit/42b64f7beea91f16dedf7f981490d73e803678db
