### ISSUE TITLE
MSCD breaks core functionalities

### ISSUE THREAD

**Issue by fliespl** [pierre-dargham/multisite-clone-duplicator#5]
MSCD forces check on admin referer, but doesn't check if $_POST is delegated for it. In this case i. e. delete blog functionality fails (check_admin_referer throws 403). 

Delete blog has referer named 'confirm', but plugin checks for siteoptions (even though form is not for it). Forms should have hidden value which would allow to check if $_POST request is for plugin or not.

`if ( ! empty( $_POST ) && check_admin_referer( 'siteoptions' ) )`

**Comment by pierre-dargham** [comment]
Thank you, I didn't made enough test when releasing last versions.

I will fix this bug during the week and release a new minor version at the end of the week (unless you want to push a pull request :) )

Best regards,

Pierre

**Comment by pierre-dargham** [comment]
All right,

I fixed it : https://github.com/pierre-dargham/multisite-clone-duplicator/commit/c2ebc5b8e0bf8f6ce991dc6c01340c38193656fb

**Comment by fliespl** [comment]
Haha, you fixed it sooner than I got to forking repo :) 

Appreciate your work - thanks!

**Comment by pierre-dargham** [comment]
I'm glad our plugin could help you !

If you want to support us, [a 5-stars rating on wordpress.org](https://wordpress.org/support/view/plugin-reviews/multisite-clone-duplicator?filter=5#postform) would be nice :)
