### ISSUE TITLE
After duplication screen is empty

### ISSUE THREAD

**Issue by datafeedr** [pierre-dargham/multisite-clone-duplicator#55]
Hi

Not sure if this is a bug or not but after duplicating a site the content area is blank. There's no success message or redirect to back to /network/sites.php.

I've posted a screenshot of what I mean. I'm using version Version 1.4.1.

Thanks
Eric

<img width="820" alt="after-duplication" src="https://cloud.githubusercontent.com/assets/3752508/22249708/0d61d08e-e212-11e6-8fdc-b9942b2efa59.png">

**Comment by pierre-dargham** [comment]
You should have something like this, followed by a new start duplication page :

![screenshot-4](https://cloud.githubusercontent.com/assets/6932545/22258917/a1ed8418-e263-11e6-894d-6f5dd4102771.png)

You seems to have some php error blocking at the end of the process.

Questions :

1. Does the new site seem a valid clone ?
2. Do you have the duplication log ?
3. Do you have php errors in your servers logs ?

**Comment by datafeedr** [comment]
It appears to be working now.... I might have a directory permission issue. That might have been the issue all along. Thanks!

**Comment by pierre-dargham** [comment]
Ok, :+1: good news

If the plugin was useful to you, we always like to have more [5 stars rating ](https://wordpress.org/support/plugin/multisite-clone-duplicator/reviews/?filter=5#new-post) =D

Bests regards,
Pierre
