### ISSUE TITLE
WooCommerce support - Foreign key ?

### ISSUE THREAD

**Issue by herewithme** [pierre-dargham/multisite-clone-duplicator#87]
An error occurs during a duplication with WooCommerce. 

![Capture d’écran 2019-05-14 à 16 14 15](https://user-images.githubusercontent.com/898608/57815548-27dbae00-7778-11e9-8551-35ce9dccb9a4.png)

**Comment by davddo** [comment]
Bonjour Amaury,

Pourrais tu préciser la version de WP et celle de Woocommerce ?

Merci,
David

**Comment by herewithme** [comment]
Hello,

WooCommerce 3.6.x
WP 5.1.x

**Comment by davddo** [comment]
Je n'arrive pas à reproduire cette erreur dans cette configuration.
Il semblerait que la table "msm_asso_12_woocommerce_downloadable_product_permissions" soit déjà existante avant la duplication, et qui ne devrait pas l'être (action manuelle? autre plugin?)

**Comment by herewithme** [comment]
Nous n'avons pas reproduit l'erreur depuis ... tant mieux ! Merci pour le support ;)
